### ISSUE TITLE
TODO Jeroen

### ISSUE THREAD

**Issue by jvanstraten** [QuTech-Delft/cQASM-spec#18]
- [x] clean up old issues
 - [ ] write document describing the context of this whole thing; how I/we envision the OpenQL/QI/QX/etc ecosystem evolving as a result of this proposal, and/or how this proposal helps the natural evolution of the ecosystem
 - [ ] work out grammar
 - [ ] add examples based on [use cases](https://github.com/DiCarloLab-Delft/ElecPrj_QYASM/tree/dev-wouter/qasm)
